# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170823_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='img',
            field=models.ImageField(upload_to='products_images/'),
        ),
    ]
